package nl.partycentrum.lux.domain;

public enum MailLogType {
    OFFERTE_VERZONDEN,
    BEZICHTIGING_BEVESTIGING,
    BEZICHTIGING_HERINNERING,
    BEVESTIGINGSMAIL,
    BETALING_HERINNERING_AANBETALING,
    BETALING_HERINNERING_RESTANT,
    EVENEMENT_HERINNERING,
    REVIEW_VERZOEK,
    ANNULERING
}
