ALTER TABLE company_settings
    ADD COLUMN IF NOT EXISTS logo_base64 TEXT,
    ADD COLUMN IF NOT EXISTS brand_color VARCHAR(20) NOT NULL DEFAULT '#C9A84C',
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(30) NOT NULL DEFAULT '1000 AA',
    ADD COLUMN IF NOT EXISTS city VARCHAR(120) NOT NULL DEFAULT 'Amsterdam',
    ADD COLUMN IF NOT EXISTS kvk VARCHAR(80) NOT NULL DEFAULT '00000000',
    ADD COLUMN IF NOT EXISTS phone VARCHAR(80) NOT NULL DEFAULT '+31 20 000 0000',
    ADD COLUMN IF NOT EXISTS email VARCHAR(180) NOT NULL DEFAULT 'info@partycentrumlux.nl',
    ADD COLUMN IF NOT EXISTS website VARCHAR(180) NOT NULL DEFAULT 'www.partycentrumlux.nl';
