package nl.partycentrum.lux.dto.booking;

import nl.partycentrum.lux.domain.BookingStatus;
import nl.partycentrum.lux.domain.ContractStatus;
import nl.partycentrum.lux.domain.EventType;
import nl.partycentrum.lux.dto.subprijs.SubPrijsResponse;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.List;

public record BookingResponse(
        Long id,
        Long customerId,
        String customerName,
        String klantNaam,
        String customerEmail,
        String customerPhone,
        String customerAddress,
        LocalDate evenementDatum,
        LocalDate eventDate,
        LocalDate date,
        LocalDate endDate,
        LocalTime startTijd,
        LocalTime startTime,
        LocalTime eindTijd,
        LocalTime endTime,
        EventType evenementType,
        EventType eventType,
        int aantalGasten,
        int guestCount,
        BigDecimal subtotaal,
        BigDecimal korting,
        BigDecimal totaal,
        BigDecimal price,
        int aanbetalingPercentage,
        BigDecimal aanbetalingBedrag,
        BigDecimal restantBedrag,
        LocalDate aanbetalingDeadline,
        LocalDate restantDeadline,
        List<SubPrijsResponse> subPrijzen,
        BookingStatus status,
        String notes,
        List<String> eigenschappen,
        List<String> properties,
        String conditions,
        String offerteCustomerMessage,
        ContractStatus contractStatus,
        String docusealSubmissionId,
        LocalDate offerteDatum,
        LocalDate offerteSentDate,
        LocalDate ondertekeningDatum,
        LocalDate contractSignedDate,
        boolean aanbetalingBetaald,
        LocalDate aanbetalingBetaaldDatum,
        boolean restantBetaald,
        LocalDate restantBetaaldDatum,
        String offertePdfPath,
        String annuleringsReden,
        Long invoiceId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
) {
}
